### ISSUE TITLE
Incorrect cast of ColumnType.float to DECIMAL in SQL

### ISSUE THREAD

**Issue by kevinelliott** [angel-dart/orm#101]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/213.

**Comment by thosakwe** [comment]
Question - does the generated migration file also have `decimal`? Or `float`? IIRC I specifically added the `DECIMAL` casts because the `postgres` library returned doubles as strings (not sure if it still does this, but didn't want to fix what wasn't broken).

**Comment by kevinelliott** [comment]
I don't use the migrations (database is defined elsewhere), so I can't say there. Postgres returns the FLOAT as a number not a string.

**Comment by kevinelliott** [comment]
@thosakwe Any further update here?

**Comment by thosakwe** [comment]
Sorry, won't be able to do much this week, as I have final exams.

**Comment by kevinelliott** [comment]
OK understandable, I will fork and make some kind of correction for myself in the meantime. Thanks.

**Comment by thosakwe** [comment]
Feel free to send in a PR if you get it fixed on your end.
