### ISSUE TITLE
[Error] PostgreSQLSeverity.error 42P01 when get data from table

### ISSUE THREAD

**Issue by tvc12** [angel-dart/orm#102]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/212.

**Comment by thosakwe** [comment]
Have you run any migrations? If not, your table won't exist in the database.

**Comment by tvc12** [comment]
Category exists in my database. 
I'm try rename tableName: Category -> "Category"
```
  @override
  get tableName {
    return '"Category"';
  }
```
It's ok.

**Comment by thosakwe** [comment]
So, are you still having an error? A class named `Category` will create a table named `categories`.

**Comment by tvc12** [comment]
@thosakwe no, class named `Category` will created table named Category. but when i select it by getter `tableName`
```
@override
get tableName {
    return 'Category';
}
```
I have error: `PostgreSQLSeverity.error 42P01 when get data from table Category`
Then i add double quotation marks **"** into getter  `tableName`, it work:
```
@override
get tableName {
    return '"Category"';
}
```
