### ISSUE TITLE
Joins

### ISSUE THREAD

**Issue by thosakwe** [angel-dart/orm#23]

**Comment by ooasis** [comment]
Any plan to support joins?

**Comment by thosakwe** [comment]
Angel ORM now supports joins. Example:

```dart
var query = new FooQuery();
query.leftJoin('bars', 'id', 'foo_id');
```

Inner joins, right joins, full outer joins, self joins, and cross joins are supported.

Relations, like `@hasOne`, `@belongsTo`, etc. all use the join support under-the-hood.

Note that if you're performing a join, the actual deserialization of the returned row is in `<MyModel>Query.deserialize`. The generator spits out code that should work out-of-the-box, even when relations are present.

If you are performing a custom join at runtime, you should either:
* Override `deserialize` in a custom class (probably easiest)
* Call `executor.query` directly, after calling `query.compile()`, then:
  * Using `<MyModel>Query.parseRow` to parse some of the values from the row into a model
  * Using data from the rest of the row (it's a `List`) as you see fit.

Down the line, if this feature is requested enough (probably will be), additional runtime support can be added to make this easier.

For now, though, I'll treat it as YAGNI so that I can get a release out to begin with.
