### ISSUE TITLE
Feature request: Supporting enum types 

### ISSUE THREAD

**Issue by lasseschmitt** [angel-dart/orm#26]
https://www.postgresql.org/docs/9.1/static/datatype-enum.html

**Comment by thosakwe** [comment]
I can't think of how this would work in Dart, which only has integer based enum support.

You can easily just create an abstract class with constant values.

```dart
abstract class AccountStanding {
  const String good = 'good', probation = 'probation', banned = 'banned';
}

var query = new AccountQuery()
  ..where.standing.equals(AccountStanding.banned);

var bannedUsers = await query.get(...);
```

**Comment by lasseschmitt** [comment]
Thanks @thosakwe with the abstract class works.
