### ISSUE TITLE
Feature request: Ignoring Values / getter setter values

### ISSUE THREAD

**Issue by lasseschmitt** [angel-dart/orm#27]
Imagine the following case: 

```
DateTime birthday;
String get nicePrintedDate => birthday.toString();
```

it should be possible to ignore the `nicePrintedDate`

**Comment by thosakwe** [comment]
What do you mean by "ignore" it?

**Comment by thosakwe** [comment]
https://github.com/angel-dart/serialize#excluding-keys

**Comment by lasseschmitt** [comment]
Thanks @thosakwe  `@exclude` was what I was looking for
