### ISSUE TITLE
Error when query emails 

### ISSUE THREAD

**Issue by lasseschmitt** [angel-dart/orm#28]
When I try to query a table with equal I get the following message: 

```
 var users = new UserQuery();
 users.where.email.equals(query["email"]);
 users.limit = 1;

      try{
          var foundUser = await users.get(connection).toList();
          print(foundUser);
          return foundUser;
        }
        catch(error) {
          print(error);
        }
```

`Format string specified identifier with name 1033edge, but key was not present in values. Format string: SELECT id, username, last_name, first_name, password, phone, salt, score, verified, user_type, email, created_at, updated_at FROM "users" WHERE users.email = 'veronique.likens@1033edge.com' LIMIT 1;`

**Comment by thosakwe** [comment]
Angel ORM uses `package:postgresql`, which escapes variables with an `@`. Thus, the `@` symbol in strings should be escaped.

I think it would be smart to open an issue in https://github.com/stablekernel/postgresql-dart
