### ISSUE TITLE
Infinitif loop

### ISSUE THREAD

**Issue by lasseschmitt** [angel-dart/orm#29]
I create a scenario where an infinitive loop happens 

```
@serializable
@orm
class _User extends Model {
  @HasOne()
  Student student;
}
```

```
@serializable
@orm
class _Student extends Model {
  @BelongsTo()
  User user;
}
```

Once I call insert on the `Student` model I get an infinity loop 

`var newStudent = await StudentQuery.insertStudent(connection, student, addressId: int.parse(address.id), userId: int.parse(user.id));`

Did I miss something or did something wrong?

**Comment by thosakwe** [comment]
The two models should be built in two separate build phases if one depends on another:

```dart
new BuildAction(
    new LibraryBuilder(
      const PostgresOrmGenerator(),
      generatedExtension: '.orm.g.dart',
    ),
    packageName,
    inputs: standaloneModels,
  ),
  new BuildAction(
    new LibraryBuilder(
      const PostgresOrmGenerator(),
      generatedExtension: '.orm.g.dart',
    ),
    packageName,
    inputs: dependentModels,
  ),
```

Look at https://github.com/angel-dart/orm/blob/master/angel_orm_generator/tool/actions.dart for the full sample.

**Comment by lasseschmitt** [comment]
Thanks. Solved my problem
