### ISSUE TITLE
@BelongsTo should be optional. 

### ISSUE THREAD

**Issue by lasseschmitt** [angel-dart/orm#33]
Right now `@BelongsTo` fields not allowing `null` values. In case of #31 

The table `Books` must have a `author` but don't need to have an `partnerAuthor`  https://github.com/angel-dart/orm/pull/32/files#diff-1e229c1d5fb38ed9256e66fca2d16407R16

**Comment by thosakwe** [comment]
Not yet published, but this has been resolved now.
