### ISSUE TITLE
order by not working

### ISSUE THREAD

**Issue by moczix** [angel-dart/orm#59]
`userTokensQuery..where.userId.equals(int.parse(foundUser.id))..orderBy('expired_at', descending: true);`

query:
`[FINE] angel_orm_postgres: Query: SELECT user_tokens.id, user_tokens.token, user_tokens.expired_at, user_tokens.user_id, user_tokens.created_at, user_tokens.updated_at, a0.id, a0.username, a0.google_account_id, a0.google_account_email, a0.picture, a0.is_active, a0.is_suspended, a0.created_at, a0.updated_at FROM user_tokens  LEFT JOIN users a0 ON user_tokens.user_id=a0.id WHERE user_tokens.user_id = 4 expired_at DESC`

error: 
[INFO] angel: PostgreSQLSeverity.error 42601: syntax error at or near "expired_at"

i thinkg in query is missing "ORDER BY" key :P

**Comment by thosakwe** [comment]
Thanks! Hadn’t noticed that. I have an issue open to add more tests for
this.

**Comment by thosakwe** [comment]
Resolved via angel_orm@2.0.0-dev.24.
