### ISSUE TITLE
Foreign key indexing and not-null

### ISSUE THREAD

**Issue by sanmadjack** [angel-dart/orm#76]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/224.

**Comment by thosakwe** [comment]
Hmm... See what happens if you add a `@notNull` annotation.

**Comment by sanmadjack** [comment]
Changed to:
```
  @Column(indexType: IndexType.standardIndex)
  @BelongsTo()
  @notNull
  _ImportBatch get importBatch;
```
migrate refreshed and the foreign key column is still set to allow nulls.

**Comment by sanmadjack** [comment]
I'm currently running:
  angel_orm 2.0.0
  angel_orm_generator 2.0.4
  angel_orm_postgres 1.0.0

**Comment by thosakwe** [comment]
Thanks. I'll likely be able to roll out a fix for this tonight, but at the moment, I'm currently studying.

**Comment by sanmadjack** [comment]
I'm willing to help out to code some of this stuff if you point me at the package that it would need addressed in.

**Comment by thosakwe** [comment]
Are you still getting this error?
