### ISSUE TITLE
Migrations do not work within applications deployet as snapshots

### ISSUE THREAD

**Issue by vadimtsushko** [angel-dart/orm#83]
*This issue was automatically moved to: https://github.com/angel-dart/angel/issues/220.

**Comment by thosakwe** [comment]
Apologies for the late response.

A possible solution is maybe including that information in the generated migration class. It's pretty feasible:

```dart
class MyMigration extends Migration {
  @override
  String get sourceHash => 'package:foo/lib/src/models.dart#_MyClass';
}
```

The only thing is that this would be a breaking change for existing migrations. Perhaps a fallback could use `package:stack_trace` and some other hackery to figure out the class name:

```dart
// pseudocode:
String get sourceHash {
  String file, className;
  var trace = Trace.current();
  file = trace.frames.first.filename;
  className = runtimeType.toString();
  return file + '#' + className;
}
```
